#!/usr/bin/env python3
"""Validate a persistent InTAS-derived MOSAIC literature scenario.

This validator intentionally uses only Python's standard library. It verifies
that the scenario has a real SQLite database generated by Scenario-Convert and
that all text configuration produced by the materializer still points to
existing files.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sqlite3
import sys
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


STATUS_VALID = "VALID_MATERIALIZED_SCENARIO"
STATUS_INVALID = "INVALID_MATERIALIZED_SCENARIO"
SCENARIO_NAME = "MaGaLiteratureBasedUrbanStudy"
DB_NAME = "intas_literature_urban.db"
TOKEN_MARKERS = ("${", "<derived-", "<subscenario>")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Validate a persistent MaGa literature MOSAIC scenario.")
    parser.add_argument("--scenario-root", required=True, help="Persistent scenario root.")
    parser.add_argument("--repo-root", default=None, help="Repository root for diagnostic DB comparison.")
    parser.add_argument(
        "--json-output",
        default=None,
        help="Output JSON path. Defaults to <scenario-root>/reports/materialized_literature_scenario_validation.json.",
    )
    return parser.parse_args()


def load_json(path: Path, errors: list[str]) -> dict[str, Any]:
    try:
        return json.loads(path.read_text(encoding="utf-8-sig"))
    except FileNotFoundError:
        errors.append(f"Missing JSON file: {display(path)}")
    except json.JSONDecodeError as exc:
        errors.append(f"Invalid JSON {display(path)}: {exc}")
    return {}


def display(path: Path) -> str:
    return str(path).replace("\\", "/")


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def has_sqlite_header(path: Path) -> bool:
    with path.open("rb") as handle:
        return handle.read(16) == b"SQLite format 3\x00"


def inspect_sqlite(path: Path, errors: list[str]) -> dict[str, Any]:
    if not path.exists():
        errors.append(f"Database missing: {display(path)}")
        return {"tables": [], "tableCounts": {}, "readable": False}
    if path.stat().st_size <= 0:
        errors.append(f"Database is empty: {display(path)}")
    if not has_sqlite_header(path):
        errors.append(f"Database does not have a SQLite header: {display(path)}")
        return {"tables": [], "tableCounts": {}, "readable": False}

    table_counts: dict[str, int | None] = {}
    try:
        with sqlite3.connect(path) as connection:
            table_rows = connection.execute(
                "select name from sqlite_master where type='table' order by name"
            ).fetchall()
            tables = [row[0] for row in table_rows]
            if not tables:
                errors.append("SQLite database has no tables.")
            for table in tables:
                try:
                    count = connection.execute(f'select count(*) from "{table}"').fetchone()[0]
                except sqlite3.Error:
                    count = None
                table_counts[table] = count
            if not any((count or 0) > 0 for count in table_counts.values()):
                errors.append("SQLite database has no table with count > 0.")
            return {"tables": tables, "tableCounts": table_counts, "readable": True}
    except sqlite3.Error as exc:
        errors.append(f"SQLite database is not readable: {exc}")
        return {"tables": [], "tableCounts": {}, "readable": False}


def diagnostic_db_hashes(repo_root: Path | None) -> dict[str, str]:
    if repo_root is None or not repo_root.exists():
        return {}
    candidates = [
        repo_root / "data" / "mosaic-scenarios" / "MaGaLiveMagaRuntimeStudy" / "application" / "Barnim.db",
        *repo_root.glob("archive/historical-scenarios/**/application/*.db"),
    ]
    hashes: dict[str, str] = {}
    for candidate in candidates:
        if candidate.exists() and candidate.is_file():
            hashes[display(candidate)] = sha256(candidate)
    return hashes


def scan_tokens(root: Path) -> list[str]:
    matches: list[str] = []
    for path in root.rglob("*"):
        if path.is_dir() or path.suffix.lower() not in {".json", ".xml", ".sumocfg"}:
            continue
        if "reports" in path.parts:
            continue
        text = path.read_text(encoding="utf-8-sig", errors="replace")
        if any(marker in text for marker in TOKEN_MARKERS):
            matches.append(display(path))
    return sorted(matches)


def sumocfg_references(sumocfg_path: Path) -> list[str]:
    tree = ET.parse(sumocfg_path)
    refs: list[str] = []
    for node in tree.getroot().iter():
        tag = node.tag.split("}")[-1]
        if tag in {"net-file", "route-files", "additional-files"}:
            refs.extend(item.strip() for item in node.attrib.get("value", "").split(",") if item.strip())
    return refs


def reduced_network_counts(path: Path, errors: list[str]) -> dict[str, int]:
    try:
        root = ET.parse(path).getroot()
    except (FileNotFoundError, ET.ParseError) as exc:
        errors.append(f"Cannot inspect reduced SUMO network: {exc}")
        return {"externalEdges": 0, "externalJunctions": 0, "trafficLights": 0}
    edges = [node for node in root.iter() if node.tag.split("}")[-1] == "edge" and not node.attrib.get("id", "").startswith(":")]
    junctions = [node for node in root.iter() if node.tag.split("}")[-1] == "junction" and not node.attrib.get("id", "").startswith(":") and node.attrib.get("type") != "internal"]
    traffic_lights = [node for node in junctions if node.attrib.get("type") == "traffic_light"]
    return {"externalEdges": len(edges), "externalJunctions": len(junctions), "trafficLights": len(traffic_lights)}


def route_vehicle_counts(paths: list[Path], errors: list[str]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for path in paths:
        try:
            root = ET.parse(path).getroot()
            counts[path.name] = sum(1 for node in root.iter() if node.tag.split("}")[-1] == "vehicle")
        except ET.ParseError as exc:
            errors.append(f"Invalid route XML {display(path)}: {exc}")
    return counts


def validate(scenario_root: Path, repo_root: Path | None) -> dict[str, Any]:
    root = scenario_root.resolve()
    errors: list[str] = []
    warnings: list[str] = []

    if not root.exists():
        errors.append(f"Scenario root missing: {display(root)}")
    if root.name != SCENARIO_NAME and not (root / "scenario_config.json").exists():
        warnings.append("Scenario root name does not match the canonical scenario name.")

    required_paths = [
        "scenario_config.json",
        "application/application_config.json",
        "application/ma_ga_live_state_config.json",
        "application/ma_ga_live_runtime_config.json",
        "application/ma_ga_calibration_metadata.json",
        f"application/{DB_NAME}",
        "mapping/mapping_config.json",
        "sns/sns_config.json",
        "cell/cell_config.json",
        "cell/network.json",
        "cell/regions.json",
        "sumo/intas_literature_urban.net.xml",
        "sumo/intas_literature_urban.sumocfg",
        "sumo/sumo_config.json",
        "output/output_config.xml",
        "reports/intas_literature_materialization_report.json",
        "materialization_manifest.json",
    ]
    missing = []
    for relative in required_paths:
        if not (root / relative).exists():
            missing.append(relative)
            errors.append(f"Required materialized scenario file missing: {relative}")

    scenario = load_json(root / "scenario_config.json", errors)
    app_config = load_json(root / "application" / "application_config.json", errors)
    load_json(root / "mapping" / "mapping_config.json", errors)
    load_json(root / "sns" / "sns_config.json", errors)
    load_json(root / "cell" / "cell_config.json", errors)
    load_json(root / "cell" / "network.json", errors)
    load_json(root / "cell" / "regions.json", errors)
    load_json(root / "application" / "ma_ga_live_state_config.json", errors)
    load_json(root / "application" / "ma_ga_live_runtime_config.json", errors)
    report = load_json(root / "reports" / "intas_literature_materialization_report.json", errors)
    manifest = load_json(root / "materialization_manifest.json", errors)

    projection = scenario.get("simulation", {}).get("projection", {})
    center = projection.get("centerCoordinates", {})
    offset = projection.get("cartesianOffset", {})
    for name, value in {
        "projection.centerCoordinates.latitude": center.get("latitude"),
        "projection.centerCoordinates.longitude": center.get("longitude"),
        "projection.cartesianOffset.x": offset.get("x"),
        "projection.cartesianOffset.y": offset.get("y"),
    }.items():
        if not isinstance(value, (int, float)):
            errors.append(f"{name} must be numeric in scenario_config.json.")

    configured_db = (
        app_config.get("navigationConfiguration", {}).get("databaseFile")
        or app_config.get("navigation", {}).get("databaseFile")
    )
    if configured_db != DB_NAME:
        errors.append(f"application_config.json must point to {DB_NAME}, found {configured_db!r}.")

    sumocfg = root / "sumo" / "intas_literature_urban.sumocfg"
    sumocfg_refs: list[str] = []
    if sumocfg.exists():
        try:
            sumocfg_refs = sumocfg_references(sumocfg)
            for ref in sumocfg_refs:
                if not (sumocfg.parent / ref).resolve().exists():
                    errors.append(f"sumocfg reference is missing: {ref}")
        except ET.ParseError as exc:
            errors.append(f"Invalid SUMO config XML: {exc}")

    route_paths = sorted((root / "sumo").glob("*.rou.xml"))
    route_files = [display(path) for path in route_paths]
    if not route_files:
        errors.append("No SUMO route file found under sumo/.")
    route_counts = route_vehicle_counts(route_paths, errors)

    net_counts = reduced_network_counts(root / "sumo" / "intas_literature_urban.net.xml", errors)
    for key, expected in (("externalEdges", 155), ("externalJunctions", 88), ("trafficLights", 8)):
        if net_counts.get(key) != expected:
            errors.append(f"Reduced network {key} expected {expected}, found {net_counts.get(key)!r}.")

    if report.get("mobilityMode") != "SYNTHETIC_CALIBRATED_ON_INTAS_SUBNETWORK":
        errors.append("Materialization report must declare synthetic-calibrated InTAS mobility mode.")
    if report.get("selectedCandidateId") != "candidate_0045":
        errors.append("Materialization report must use candidate_0045.")
    if manifest.get("mobilityMode") != "SYNTHETIC_CALIBRATED_ON_INTAS_SUBNETWORK":
        errors.append("Materialization manifest must declare synthetic-calibrated InTAS mobility mode.")
    route_subsets = report.get("routeSubsets", {})
    if not route_subsets:
        errors.append("Materialization report has no synthetic route subsets.")
    for density, subset in route_subsets.items():
        validation = subset.get("mobilityValidation", {})
        fcd = validation.get("fcd", {})
        logs = validation.get("logs", {})
        if validation.get("status") != "VALID_SYNTHETIC_MOBILITY":
            errors.append(f"Synthetic mobility validation failed for {density}.")
        if int(fcd.get("gatewaySwitchEvents", 0)) <= 0:
            errors.append(f"Synthetic mobility has no gateway switches for {density}.")
        if int(logs.get("errorCount", -1)) != 0:
            errors.append(f"SUMO error count is not zero for {density}.")
        if int(logs.get("teleportMentions", -1)) != 0:
            errors.append(f"SUMO teleport count is not zero for {density}.")
        if int(logs.get("emergencyBrakingMentions", -1)) != 0:
            errors.append(f"SUMO emergency-braking count is not zero for {density}.")
    nominal = route_subsets.get("nominal")
    if nominal is not None:
        nominal_fcd = nominal.get("mobilityValidation", {}).get("fcd", {})
        mean_active = float(nominal_fcd.get("meanActiveVehicles", 0.0))
        if not 28.0 <= mean_active <= 36.0:
            errors.append(f"Nominal mean active vehicles expected in [28, 36], found {mean_active}.")
        if int(nominal.get("vehicleCount", 0)) != 50:
            errors.append(f"Nominal synthetic vehicle count expected 50, found {nominal.get('vehicleCount')!r}.")

    if list(root.rglob("*.jar")):
        errors.append("Materialized scenario must not contain JAR files before deploy.")
    if list(root.rglob("*.pyc")):
        errors.append("Materialized scenario must not contain pyc files.")

    token_files = scan_tokens(root)
    if token_files:
        errors.append(f"Template tokens remain in concrete materialized files: {token_files}")

    db_path = root / "application" / DB_NAME
    db_info = inspect_sqlite(db_path, errors)
    db_hash = sha256(db_path) if db_path.exists() else None
    diag_hashes = diagnostic_db_hashes(repo_root)
    matching_diagnostics = [
        path for path, digest in diag_hashes.items() if db_hash is not None and digest == db_hash
    ]
    if matching_diagnostics:
        errors.append(f"Materialized DB is identical to diagnostic DB(s): {matching_diagnostics}")

    result = {
        "status": STATUS_VALID if not errors else STATUS_INVALID,
        "scenarioRoot": display(root),
        "generatedAtUtc": datetime.now(timezone.utc).isoformat(),
        "missingFiles": missing,
        "database": {
            "path": display(db_path),
            "exists": db_path.exists(),
            "sizeBytes": db_path.stat().st_size if db_path.exists() else 0,
            "sha256": db_hash,
            "readable": db_info["readable"],
            "tables": db_info["tables"],
            "tableCounts": db_info["tableCounts"],
            "matchingDiagnosticDbs": matching_diagnostics,
        },
        "configuredDatabaseFile": configured_db,
        "projection": projection,
        "sumocfgReferences": sumocfg_refs,
        "routeFiles": route_files,
        "routeVehicleCounts": route_counts,
        "reducedNetworkCounts": net_counts,
        "mobilityMode": report.get("mobilityMode"),
        "tokenFiles": token_files,
        "warnings": warnings,
        "errors": errors,
    }
    return result


def write_markdown(path: Path, result: dict[str, Any]) -> None:
    db = result["database"]
    lines = [
        "# Materialized Literature Scenario Validation",
        "",
        f"- status: `{result['status']}`",
        f"- scenario root: `{result['scenarioRoot']}`",
        f"- database: `{db['path']}`",
        f"- database size bytes: `{db['sizeBytes']}`",
        f"- database sha256: `{db['sha256']}`",
        f"- database readable: `{db['readable']}`",
        "",
        "## Tables",
        "",
    ]
    for table, count in db["tableCounts"].items():
        lines.append(f"- `{table}`: `{count}`")
    lines.extend(["", "## Errors", ""])
    lines.extend(f"- {error}" for error in result["errors"])
    lines.extend(["", "## Warnings", ""])
    lines.extend(f"- {warning}" for warning in result["warnings"])
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    args = parse_args()
    root = Path(args.scenario_root).resolve()
    repo_root = Path(args.repo_root).resolve() if args.repo_root else None
    output = Path(args.json_output).resolve() if args.json_output else root / "reports" / "materialized_literature_scenario_validation.json"
    output.parent.mkdir(parents=True, exist_ok=True)
    result = validate(root, repo_root)
    output.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    write_markdown(output.parent / "materialized_literature_scenario_validation.md", result)
    print(json.dumps(result, indent=2, sort_keys=True))
    return 0 if result["status"] == STATUS_VALID else 2


if __name__ == "__main__":
    sys.exit(main())
