package validation.snapshot;

import model.bandwidth.BandwidthPoolResolver;
import model.node.NodeCandidate;
import model.node.NodeType;
import model.snapshot.*;

import java.util.*;

/** Validazione strutturale finale per pool globali, gateway e V2V. */
public final class SnapshotValidator {
    public void validate(SystemSnapshot s){Objects.requireNonNull(s,"snapshot must not be null."); requireText(s.getSnapshotId(),"snapshotId");
        Set<String>vehicles=idsVehicles(req(s.getVehicles(),"vehicles")); List<TaskInstance>tasks=req(s.getTasks(),"tasks"); List<NodeCandidate>candidates=req(s.getCandidateNodes(),"candidateNodes"); Set<String>gateways=idsGateways(req(s.getAccessGateways(),"accessGateways")); Set<String>pools=idsPools(req(s.getBandwidthPools(),"bandwidthPools"));
        uniqueTasks(tasks); uniqueCandidates(candidates); links(req(s.getAccessLinks(),"accessLinks"),vehicles,gateways); gatewayPools(s.getAccessGateways(),pools); tasks(tasks,vehicles,candidates); candidates(s,candidates,vehicles); }
    private void gatewayPools(List<AccessGatewaySnapshot> g,Set<String>p){for(AccessGatewaySnapshot x:g)if(x.getBandwidthPoolId()!=null&&!p.contains(x.getBandwidthPoolId()))throw new IllegalArgumentException("Gateway "+x.getGatewayId()+" references missing bandwidth pool "+x.getBandwidthPoolId());}
    private void candidates(SystemSnapshot s,List<NodeCandidate>cs,Set<String>vehicles){BandwidthPoolResolver r=new BandwidthPoolResolver();for(NodeCandidate c:cs){ref(vehicles,c.getSourceVehicleId(),"candidate source vehicle");if(c.getType()==NodeType.LOCAL){if(!c.getSourceVehicleId().equals(c.getExecutionNodeId()))throw new IllegalArgumentException("Invalid LOCAL candidate: "+c.getCandidateId());continue;}if(c.getType()==NodeType.VEHICLE&&c.getSourceVehicleId().equals(c.getExecutionNodeId()))throw new IllegalArgumentException("Invalid VEHICLE candidate: "+c.getCandidateId());r.resolve(s,c);}}
    private void tasks(List<TaskInstance>ts,Set<String>vehicles,List<NodeCandidate>cs){for(TaskInstance t:ts){ref(vehicles,t.getSourceVehicleId(),"task source vehicle");boolean local=false;for(NodeCandidate c:cs)if(c.isValidForSourceVehicle(t.getSourceVehicleId())&&c.getType()==NodeType.LOCAL)local=true;if(!local)throw new IllegalArgumentException("Task "+t.getTaskId()+" has no LOCAL candidate.");}}
    private void links(List<AccessLinkSnapshot>ls,Set<String>vehicles,Set<String>gateways){Set<String>ids=new HashSet<>();Map<String,Integer>a=new HashMap<>();for(AccessLinkSnapshot l:ls){add(ids,l.getAccessLinkId(),"accessLinkId");ref(vehicles,l.getVehicleId(),"vehicle");ref(gateways,l.getGatewayId(),"gateway");if(l.isActive())a.merge(l.getVehicleId(),1,Integer::sum);}for(String v:vehicles)if(a.getOrDefault(v,0)!=1)throw new IllegalArgumentException("Vehicle "+v+" must have exactly one active access link.");}
    private Set<String>idsVehicles(List<VehicleSnapshot>x){Set<String>s=new HashSet<>();for(VehicleSnapshot v:x)add(s,v.getVehicleId(),"vehicleId");return s;} private Set<String>idsGateways(List<AccessGatewaySnapshot>x){Set<String>s=new HashSet<>();for(AccessGatewaySnapshot v:x)add(s,v.getGatewayId(),"gatewayId");return s;} private Set<String>idsPools(List<BandwidthPoolSnapshot>x){Set<String>s=new HashSet<>();for(BandwidthPoolSnapshot v:x)add(s,v.getPoolId(),"poolId");if(s.isEmpty())throw new IllegalArgumentException("At least one bandwidth pool is required.");return s;} private void uniqueTasks(List<TaskInstance>x){Set<String>s=new HashSet<>();for(TaskInstance v:x)add(s,v.getTaskId(),"taskId");} private void uniqueCandidates(List<NodeCandidate>x){Set<String>s=new HashSet<>();for(NodeCandidate v:x)add(s,v.getCandidateId(),"candidateId");}
    private <T>List<T>req(List<T>x,String n){if(x==null)throw new IllegalArgumentException("snapshot."+n+" must not be null.");return x;} private void add(Set<String>s,String v,String f){requireText(v,f);if(!s.add(v))throw new IllegalArgumentException("Duplicated "+f+": "+v);} private void ref(Set<String>s,String v,String l){requireText(v,l);if(!s.contains(v))throw new IllegalArgumentException("Missing "+l+": "+v);} private void requireText(String v,String f){if(v==null||v.isBlank())throw new IllegalArgumentException(f+" must not be null or blank.");}
}
